name: Ongky Wijana Art in Stone
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#404040'
    - '#757575'
    - '#9c9c9c'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
