name: Ongky Wijana Art in Stone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#50798d'
    - '#396379'
    - '#6691a4'
    - '#1d1814'
    - '#224b61'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
