name: Ongky Wijana Art in Stone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#50798d'
    - '#396379'
    - '#6691a4'
    - '#1d1814'
    - '#224b61'
  brandStrength: 0.6728093945421278
  lightness: 0.4160730300936848
  saturation: 0.8775820375885814
  rhythmicContrast: 0.1122297823894769
purpose: []
