name: Ongky Wijana Art in Stone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f7fb'
    - '#0c0c0e'
    - '#9f9073'
    - '#5b3a31'
    - '#d2bf97'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
