name: Ongky Wijana Art in Stone
favicon: null
layout_spectrum: 0.7791656262706965
typography_spectrum: 0.8461997003760189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6728093945421278
  lightness: 0.4160730300936848
  saturation: 0.8775820375885814
  rhythmicContrast: 0.1122297823894769
purpose: []
